easy_admin:
    site_name: 'Segedanyag Portal'
    design:
        brand_color: '#81b9ba'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - easy_admin/_form_theme.html.twig
        menu:
            - { entity: 'User', icon: 'user' }
            - { entity: 'ContentType', icon: 'cog' }
            - { entity: 'Training', icon: 'university' }
            - { entity: 'Subject', icon: 'fire' }
            - { entity: 'Material', icon: 'file' }
            - { entity: 'TextContent', icon: 'font' }

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        User:
            class: App\Entity\User
        ContentType:
            class: App\Entity\ContentType
        Training:
            class: App\Entity\Training
        Subject:
            class: App\Entity\Subject
            list:
                fields: ['id', 'name', 'slug', 'semester', 'subjectcode', 'training']
            form:
                fields:
                    - name
                    - slug
                    - training
                    - subjectcode
                    - semester
                    - icon
                    - { property: 'thumbnailFile', type: 'vich_image' }
                    - { property: 'description', type: 'fos_ckeditor' }
                    - { property: 'color', type: 'color' }
                    - materials
        Material:
            class: App\Entity\Material
            list:
                fields: ['id', 'title', 'slug', 'type', 'subject']
            form:
                fields:
                    - title
                    - slug
                    - type
                    - subject
                    - metadata
                    - shortDescription
                    - { property: 'description', type: 'fos_ckeditor' }
                    - { property: 'thumbnailFile', type: 'vich_image' }
                    - link
                    - file
                    -
                        property: 'fileFile'
                        type_options:
                            mapped: false
                    #- { property: 'fileFile', type: 'file' }
        TextContent:
            class: App\Entity\TextContent
            form:
                fields:
                    - identifier
                    - { property: 'content', type: 'fos_ckeditor' }
