security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_provider:
            entity: { class: App:User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path:   app_logout

            guard:
                authenticators:
                    - App\Security\SchAuthenticator
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/bsc, roles: ROLE_USER }
        - { path: ^/msc, roles: ROLE_USER }
        - { path: ^/bprof, roles: ROLE_USER }
        - { path: ^/anyagok, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }

knpu_oauth2_client:
    clients:
        sch:
            type: generic
            provider_class: App\Provider\Sch
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(resolve:SCH_CLIENT_ID)%'
            client_secret: '%env(resolve:SCH_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_sch_check
            redirect_params: {}
            # Optional value for sending access_type parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
            # access_type: ''
            # Optional value for sending hd parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
            # hosted_domain: ''
            # Optional value for additional fields to be requested from the user profile. If set, these values will be included with the defaults. More details: https://developers.google.com/+/web/api/rest/latest/people
            # user_fields: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
