vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        materials:
            uri_prefix:         '/materials'
            upload_destination: '%kernel.project_dir%/public/materials'
        thumbnails:
            uri_prefix:         '/img/thumbnails'
            upload_destination: '%kernel.project_dir%/public/img/thumbnails'
